### ISSUE TITLE
Broken with multi-command files

### ISSUE THREAD

**Issue by foxfirecodes** [I-Al-Istannen/SharpbotCommandUsageCreator#1]
Example: [animals.js](https://raw.githubusercontent.com/Rayzr522/SharpBot/master/src/commands/Fun/animals.js)

The parser fails on that file since it can't find a normal `exports.info` block. Any ideas? 

**EDIT:** Here's the error, in case you're curious:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rayzr/Desktop/SharpbotCommandUsageCreator/sharpbotcommandusagecreator/__main__.py", line 68, in <module>
    for x in commands
  File "/home/rayzr/Desktop/SharpbotCommandUsageCreator/sharpbotcommandusagecreator/__main__.py", line 68, in <listcomp>
    for x in commands
  File "/home/rayzr/Desktop/SharpbotCommandUsageCreator/sharpbotcommandusagecreator/descriptionextractor.py", line 16, in get_description
    description_dict = demjson.decode(description_json)
  File "/home/rayzr/Desktop/SharpbotCommandUsageCreator/env/lib/python3.6/site-packages/demjson.py", line 5699, in decode
    return_stats=(return_stats or write_stats) )
  File "/home/rayzr/Desktop/SharpbotCommandUsageCreator/env/lib/python3.6/site-packages/demjson.py", line 4915, in decode
    raise errors[0]
demjson.JSONDecodeError: Can not decode value starting with character '}'
```

**Comment by foxfirecodes** [comment]
Would I be correct in assuming that this utility will no longer be receiving updates?

**Comment by foxfirecodes** [comment]
Irrelevant now that SharpBot is banned.
